name: DL_env
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-project=0.10.0
  - anyio=3.1.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=1.1.0
  - asn1crypto=1.4.0
  - astroid=2.5.6
  - astropy=3.2.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.5
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.9.3
  - binaryornot=0.4.4
  - bitarray=2.0.1
  - bkcharts=0.2
  - black=21.5b0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.3.2
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=8.0.1
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda-pack=0.6.0
  - contextlib2=0.6.0.post1
  - cookiecutter=1.6.0
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - curl=7.76.1
  - cycler=0.10.0
  - cython=0.29.23
  - cytoolz=0.11.0
  - dask=2021.5.0
  - dask-core=2021.5.0
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2021.5.0
  - docutils=0.15.2
  - entrypoints=0.3
  - enum34=1.1.10
  - et_xmlfile=1.0.1
  - expat=2.3.0
  - fastcache=1.1.0
  - ffmpeg=4.3.1
  - filelock=3.0.12
  - flake8=3.8.4
  - flask=2.0.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=2021.5.0
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=21.1.2
  - glib=2.68.2
  - glib-tools=2.68.2
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.0b1
  - gnutls=3.6.13
  - google-auth=1.30.0
  - graphite2=1.3.14
  - greenlet=1.1.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.2.1
  - harfbuzz=2.8.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - html5lib=1.1
  - hypothesis=6.13.2
  - icu=58.2
  - idna=2.10
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=4.0.1
  - importlib_metadata=4.0.1
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.2.0
  - intervaltree=3.0.2
  - ipykernel=5.5.5
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=5.8.0
  - itsdangerous=2.0.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.17.2
  - jeepney=0.6.0
  - jinja2=3.0.1
  - jinja2-time=0.2.0
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.8.0
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.5.2
  - jupyterlab_widgets=1.0.0
  - keyring=23.0.1
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libarchive=3.5.1
  - libcurl=7.76.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.2
  - libiconv=1.16
  - liblief=0.11.4
  - libllvm10=10.0.1
  - libllvm9=9.0.1
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.17.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libuv=1.41.0
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvm-openmp=11.1.0
  - llvmlite=0.36.0
  - locket=0.2.0
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.0
  - mock=4.0.3
  - more-itertools=8.8.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - mypy_extensions=0.4.3
  - nbclassic=0.2.8
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.6
  - networkx=2.5.1
  - ninja=1.10.2
  - nltk=3.6.2
  - nose=1.3.7
  - notebook=6.4.0
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.13
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - partd=1.2.0
  - patchelf=0.11
  - path=15.1.2
  - path.py=12.5.0
  - pathlib=1.0.1
  - pathlib2=2.3.5
  - pathspec=0.8.1
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - pixman=0.38.0
  - pkginfo=1.7.0
  - pluggy=0.13.1
  - ply=3.11
  - pooch=1.3.0
  - poyo=0.5.0
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - prompt_toolkit=3.0.18
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.11.4
  - pyasn1=0.4.8
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pydocstyle=6.1.1
  - pyflakes=2.2.0
  - pygments=2.9.0
  - pyjwt=2.1.0
  - pylint=2.7.2
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.4
  - pytest-arraydiff=0.3
  - pytest-astropy=0.8.0
  - pytest-astropy-header=0.1.2
  - pytest-cov=2.12.0
  - pytest-doctestplus=0.9.0
  - pytest-filter-subpackage=0.1.1
  - pytest-mock=3.6.1
  - pytest-openfiles=0.5.0
  - pytest-remotedata=0.3.2
  - python=3.8.10
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-libarchive-c=2.9
  - python_abi=3.8
  - pytorch=1.8.1
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qdarkstyle=3.0.2
  - qstylizer=0.2.0
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - readline=8.1
  - regex=2021.4.4
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - ripgrep=12.1.1
  - rope=0.18.0
  - rsa=4.7.2
  - rtree=0.9.7
  - ruamel_yaml=0.15.80
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - secretstorage=3.3.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - singledispatch=3.6.1
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.0.1
  - sphinx=3.5.4
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.0.3
  - spyder-kernels=2.0.3
  - sqlalchemy=1.4.15
  - sqlite=3.35.5
  - statsmodels=0.12.0
  - sympy=1.8
  - tbb=2020.2
  - tblib=1.7.0
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.10.0
  - testpath=0.5.0
  - textdistance=4.2.1
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tifffile=2019.7.26.2
  - tinycss2=1.1.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unixodbc=2.3.9
  - urllib3=1.26.4
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.36.2
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=2.1.0
  - x264=1!161.3030
  - xlrd=2.0.1
  - xlsxwriter=1.4.3
  - xlwt=1.3.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.6.3
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - advertorch==0.2.3
    - cox==0.1.post3
    - dill==0.3.3
    - eagerpy==0.29.0
    - foolbox==3.3.1
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth-oauthlib==0.4.4
    - gputil==1.4.0
    - grpcio==1.37.1
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - progress==1.5
    - protobuf==3.15.8
    - py3nvml==0.2.6
    - pyasn1-modules==0.2.8
    - smmap==4.0.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboardx==2.2
    - torch-tb-profiler==0.1.0
    - torchcontrib==0.0.2
    - xmltodict==0.12.0
